<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
		<PackageReference Include="xunit" Version="2.7.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\BankTeller.TellerApp\BankTeller.TellerApp.csproj" />
	  <ProjectReference Include="..\..\src\BankTeller.Core\BankTeller.Core.csproj" />
	</ItemGroup>
</Project>